env:
  browser: true
  commonjs: true
  es6: true
  jest: true
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: script
rules:
  {
    'strict': 'off',
    'no-unused-vars': 'off',
    'prefer-const': 'error',
    'no-var': 'warn',
    'no-plusplus': 'off',
    'no-empty': 'off',
    'operator-assignment': 'off',
  }
